name: Convert markdown to html

on: push

defaults:
  run:
    working-directory: ".github/markdown-to-html"

jobs:
  convert-markdown:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install dependencies
        run: |
          npm ci
          npx gulp 'Convert Markdown to HTML' --input_dir '../../oni/*.md' --output_dir '../../oni'
      - name: Commit and push if it changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m 'Converted markdown to html'
          git push
